-- ============================================================
-- HUEVOS · Migración 3: pedidos de clientes y facturas
-- Ejecutar en: Supabase Dashboard -> SQL Editor
-- ============================================================

-- Pedidos hechos por clientes desde el portal
create table public.pedidos (
  id uuid primary key default gen_random_uuid(),
  customer_profile uuid not null references public.profiles (id) default auth.uid(),
  total_huevos integer not null check (total_huevos > 0),
  total_monto numeric(12,2) not null,
  estado text not null default 'PENDIENTE'
    check (estado in ('PENDIENTE', 'CONFIRMADO', 'EN_DESPACHO', 'ENTREGADO', 'CANCELADO')),
  lineas jsonb not null,
  nota text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Facturas: se generan automáticamente al marcar un pedido como ENTREGADO
create table public.facturas (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity,
  pedido_id uuid not null unique references public.pedidos (id) on delete cascade,
  monto numeric(12,2) not null,
  pagada boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.facturar_pedido()
returns trigger language plpgsql security definer as $$
begin
  new.updated_at := now();
  if new.estado = 'ENTREGADO' and old.estado is distinct from 'ENTREGADO' then
    insert into public.facturas (pedido_id, monto)
    values (new.id, new.total_monto)
    on conflict (pedido_id) do nothing;
  end if;
  return new;
end $$;

create trigger trg_facturar before update on public.pedidos
  for each row execute function public.facturar_pedido();

-- Seguridad
alter table public.pedidos enable row level security;
alter table public.facturas enable row level security;

create policy "cliente crea su pedido" on public.pedidos
  for insert to authenticated
  with check (customer_profile = auth.uid());

create policy "cliente ve sus pedidos" on public.pedidos
  for select to authenticated
  using (customer_profile = auth.uid() or public.es_admin());

create policy "admin gestiona pedidos" on public.pedidos
  for update to authenticated
  using (public.es_admin()) with check (public.es_admin());

create policy "cliente ve sus facturas" on public.facturas
  for select to authenticated
  using (
    public.es_admin()
    or exists (
      select 1 from public.pedidos p
      where p.id = pedido_id and p.customer_profile = auth.uid()
    )
  );

-- Tiempo real para el panel del admin
alter publication supabase_realtime add table public.pedidos;
